metadata: {}
pipeline:
  created_at: '2026-03-30T10:00:10.375224'
  id: PIPE-CA6099F1
  name: honey_pot
  version: 1.0.0
steps:
- name: states.yaml_read
  type: task
  version: 1.0.1
- name: states.image_inference
  type: task
  version: 1.2.1
