metadata: {}
pipeline:
  created_at: '2026-03-30T10:54:45.550741'
  id: PIPE-97CC7193
  name: honey_pot_reporter
  version: 1.0.0
steps:
- name: Inference
  type: task
  version: v1.0
- expression: score > 80
  name: <wpipe.pipe.pipe.Condition object at 0x741527c39730>
  type: condition
