import asyncio
import os
import sqlite3
import pytest
import json
import tempfile
from datetime import datetime, timedelta
from unittest.mock import MagicMock, patch

from wpipe import PipelineAsync, Condition, PipelineTracker, PipelineExporter
from wpipe.tracking.analysis import AnalysisManager
from wpipe.tracking.alerts import AlertManager
from wpipe.exception import TaskError, Codes
from wpipe.util.transform import object_to_dict, auto_dict_input, state, to_obj

@pytest.fixture
def lts_db():
    db_path = "test_lts_coverage.db"
    if os.path.exists(db_path):
        os.remove(db_path)
    # Initialize tracker to ensure tables are created via WSQLite
    tracker = PipelineTracker(db_path)
    yield db_path
    if os.path.exists(db_path):
        # We don't remove it here to allow tests to see the state if needed, 
        # but fixture will cleanup next time
        pass

# --- Async Pipeline Tests ---

@pytest.mark.asyncio
async def test_async_pipeline_full_flow(lts_db):
    """Test standard async pipeline execution with context chaining."""
    pipe = PipelineAsync(pipeline_name="LTS_Async_Test", tracking_db=lts_db)
    
    async def step1(data):
        return {"val": 1}
        
    async def step2(data):
        current_val = data.get("val", 0)
        return {"val": current_val + 1}
        
    pipe.set_steps([
        (step1, "step1", "v1"),
        (step2, "step2", "v1")
    ])
    result = await pipe.run({"initial": "data"})
    
    assert result["val"] == 2
    assert result["initial"] == "data"

@pytest.mark.asyncio
async def test_async_pipeline_retry(lts_db):
    """Test async retry logic."""
    pipe = PipelineAsync(
        pipeline_name="Retry_Async",
        max_retries=2,
        retry_delay=0.01,
        retry_on_exceptions=(RuntimeError,)
    )
    
    call_count = 0
    async def failing_step(data):
        nonlocal call_count
        call_count += 1
        if call_count < 2:
            raise RuntimeError("Temporary failure")
        return {"fixed": True}
        
    pipe.set_steps([(failing_step, "fail_test", "v1")])
    result = await pipe.run({})
    
    assert result["fixed"] is True
    assert call_count == 2

# --- Analysis & Alerts Tests ---

def test_analysis_and_alerts_api(lts_db):
    """Test AnalysisManager and AlertManager using official APIs."""
    tracker = PipelineTracker(lts_db)
    
    # 1. Register and complete pipelines to fill DB
    reg1 = tracker.register_pipeline("pipe1", [])
    tracker.complete_pipeline(reg1["pipeline_id"], output_data={"res": "ok"})
    
    reg2 = tracker.register_pipeline("pipe1", [])
    # Simulate an error
    tracker.complete_pipeline(reg2["pipeline_id"], error_message="Fallo provocado", error_step="step1")
    
    # 2. Check Analysis
    stats = tracker.analysis.get_stats()
    assert stats["total_pipelines"] >= 2
    assert stats["errors"] >= 1
    
    trends = tracker.analysis.get_trend_data(days=1)
    assert len(trends) >= 1

    # 3. Check Alerts
    hook_called = False
    def my_hook(d):
        nonlocal hook_called
        hook_called = True
        return d
        
    tracker.alerts.add_alert_threshold(
        metric="pipeline_duration_ms",
        expression=">0",
        name="instant_alert",
        steps=[my_hook]
    )
    
    # Trigger alert via API
    hooks = tracker.alerts.check_pipeline_alerts(
        pipeline_id="p_alert",
        pipeline_name="alert_test",
        status="completed",
        duration_ms=100,
        db_pipelines=tracker.db_pipelines
    )
    
    assert len(hooks) >= 1
    hooks[0]({})
    assert hook_called is True

# --- Utility Tests ---

def test_transform_utilities():
    """Test transform decorators and object conversion."""
    class MyObj:
        def __init__(self):
            self.val = 42
            
    # Test object_to_dict
    d = object_to_dict(MyObj())
    assert d["val"] == 42
    
    # Test auto_dict_input
    @auto_dict_input
    def process(data_dict):
        return data_dict["val"] * 2
        
    assert process(MyObj()) == 84
    
    # Test state decorator (LTS style)
    @state(name="Calculator", version="2.0")
    def calc(data):
        return {"result": data.get("x", 0) + 1}
        
    assert calc.NAME == "Calculator"
    assert calc.VERSION == "2.0"
    res = calc({"x": 10})
    assert res["result"] == 11

# --- Exporter Tests ---

def test_exporter_official(lts_db):
    """Test PipelineExporter using data generated by tracker."""
    tracker = PipelineTracker(lts_db)
    reg = tracker.register_pipeline("export_target", [])
    tracker.complete_pipeline(reg["pipeline_id"])
    
    exporter = PipelineExporter(lts_db)
    
    # Export JSON
    json_data = exporter.export_pipeline_logs(format="json")
    data = json.loads(json_data)
    assert any(d["name"] == "export_target" for d in data)
    
    # Export Stats
    stats_json = exporter.export_statistics()
    stats = json.loads(stats_json)
    assert stats["total_executions"] >= 1
