# These are supported funding model platforms

#github: [wisrovi]
patreon: 
open_collective: wisrovirodriguez1990
ko_fi: williamrodriguez
tidelift: 
community_bridge: wisrovi
liberapay: wisrovi
issuehunt: wisrovi
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: wisrovirod8
thanks_dev: wisrovi
custom: ['https://gofund.me/05de0d37']
