#!/usr/bin/env python3
"""
Code Quality Report Generator

Genera reportes profesionales en Markdown, HTML y PDF.

Usage:
    python generate_report.py --project . --output ./
    python generate_report.py --project . --output ./ --format md,html
"""

import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def run_command(cmd: list[str], cwd: Path) -> tuple[int, str, str]:
    """Ejecuta un comando y retorna (returncode, stdout, stderr)."""
    try:
        result = subprocess.run(
            cmd, cwd=cwd, capture_output=True, text=True, timeout=300
        )
        return result.returncode, result.stdout, result.stderr
    except subprocess.TimeoutExpired:
        return -1, "", "Command timed out"
    except Exception as e:
        return -1, "", str(e)


def parse_pylint_output(output: str) -> dict:
    """Parsea output de pylint y extrae métricas."""
    metrics = {"score": 0.0, "issues": [], "errors": 0, "warnings": 0, "conventions": 0}

    for line in output.split("\n"):
        if "Your code has been rated at" in line:
            try:
                parts = line.split("rated at")[1].split("/")[0].strip()
                metrics["score"] = float(parts)
            except (IndexError, ValueError):
                pass
        if "E:" in line and ":" in line:
            metrics["errors"] += 1
            metrics["issues"].append(("ERROR", line.strip()))
        elif "W:" in line and ":" in line:
            metrics["warnings"] += 1
            metrics["issues"].append(("WARNING", line.strip()))
        elif "C:" in line and ":" in line:
            metrics["conventions"] += 1
            metrics["issues"].append(("CONVENTION", line.strip()))

    return metrics


def parse_coverage_output(output: str) -> dict:
    """Parsea output de coverage y extrae métricas."""
    metrics = {
        "total_statements": 0,
        "covered_statements": 0,
        "coverage_percent": 0.0,
        "missing_lines": [],
    }

    lines = output.split("\n")
    for i, line in enumerate(lines):
        if "TOTAL" in line:
            parts = line.split()
            if len(parts) >= 4:
                try:
                    metrics["total_statements"] = int(parts[1])
                    metrics["covered_statements"] = int(parts[2])
                    metrics["coverage_percent"] = float(parts[3].replace("%", ""))
                except (IndexError, ValueError):
                    pass
        if "Missing" in line and i < len(lines) - 1:
            metrics["missing_lines"] = lines[i + 1].split(", ")

    return metrics


def generate_markdown_report(
    pylint_metrics: dict, coverage_metrics: dict, bandit_output: str, project_name: str
) -> str:
    """Genera reporte en Markdown."""

    status_icon = "✅" if pylint_metrics["score"] >= 9.0 else "⚠️"
    coverage_icon = "✅" if coverage_metrics["coverage_percent"] >= 85 else "⚠️"

    report = f"""# Code Quality Report - {project_name}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Status:** {status_icon} QUALITY GATE

---

## Executive Summary

| Metric | Target | Actual | Status |
|--------|--------|--------|--------|
| **Pylint Score** | ≥9.0 | {pylint_metrics["score"]:.2f}/10 | {status_icon} |
| **Test Coverage** | ≥85% | {coverage_metrics["coverage_percent"]:.1f}% | {coverage_icon} |
| **Bandit Issues** | 0 High | {pylint_metrics["errors"] + pylint_metrics["warnings"]} | {"✅" if pylint_metrics["errors"] == 0 else "⚠️"} |

---

## Code Quality Analysis

### Pylint Report

**Score:** {pylint_metrics["score"]:.2f}/10

| Category | Count |
|----------|-------|
| Errors | {pylint_metrics["errors"]} |
| Warnings | {pylint_metrics["warnings"]} |
| Conventions | {pylint_metrics["conventions"]} |

"""

    if pylint_metrics["issues"]:
        report += "\n### Top Issues\n\n"
        for level, issue in pylint_metrics["issues"][:10]:
            report += f"- **{level}:** `{issue}`\n"

    report += f"""

---

## Coverage Report

| Metric | Value |
|--------|-------|
| Statements | {coverage_metrics["total_statements"]} |
| Covered | {coverage_metrics["covered_statements"]} |
| Coverage | {coverage_metrics["coverage_percent"]:.1f}% |

"""

    if coverage_metrics["missing_lines"]:
        report += "### Missing Lines\n\n"
        for line in coverage_metrics["missing_lines"][:20]:
            report += f"- `{line}`\n"

    report += f"""

---

## Security Analysis

```
{bandit_output[:2000]}
```

---

**Report generated by Code Quality Skill**
"""

    return report


def generate_html_report(markdown_content: str, project_name: str) -> str:
    """Genera reporte HTML profesional."""

    template_path = Path(__file__).parent.parent / "references" / "html-template.html"

    if template_path.exists():
        template = template_path.read_text()
        html = template.replace("{{PROJECT_NAME}}", project_name)
        html = html.replace("{{MARKDOWN_CONTENT}}", markdown_content)
        html = html.replace("{{DATE}}", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        return html

    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Code Quality Report - {project_name}</title>
    <style>
        body {{ font-family: system-ui, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }}
        .header {{ background: #2563eb; color: white; padding: 30px; border-radius: 8px; }}
        .metric {{ display: inline-block; margin: 10px 20px; }}
        .metric-value {{ font-size: 2em; font-weight: bold; }}
        .metric-label {{ color: #ccc; }}
        pre {{ background: #1e293b; color: #e2e8f0; padding: 20px; border-radius: 8px; overflow-x: auto; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 Code Quality Report</h1>
        <div>{project_name} | {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</div>
    </div>
    <pre>{markdown_content}</pre>
</body>
</html>"""


def main():
    parser = argparse.ArgumentParser(description="Generate Code Quality Reports")
    parser.add_argument("--project", "-p", required=True, help="Project directory")
    parser.add_argument("--output", "-o", required=True, help="Output directory")
    parser.add_argument(
        "--format", "-f", default="md,html", help="Output formats: md,html,pdf"
    )
    parser.add_argument("--name", "-n", default="Project", help="Project name")
    args = parser.parse_args()

    project_path = Path(args.project).resolve()
    output_path = Path(args.output).resolve()
    output_path.mkdir(parents=True, exist_ok=True)

    print(f"🔍 Analyzing {project_path}...")

    print("  Running pylint...")
    _, pylint_out, _ = run_command(
        [
            "python",
            "-m",
            "pylint",
            "--disable=import-error,no-member,no-name-in-module",
            "app/",
            "--output-format=text",
        ],
        project_path,
    )
    pylint_metrics = parse_pylint_output(pylint_out)

    print("  Running pytest with coverage...")
    _, coverage_out, _ = run_command(
        [
            "python",
            "-m",
            "pytest",
            "tests/",
            "--cov=.",
            "--cov-report=term-missing",
            "--cov-report=term",
            "-v",
        ],
        project_path,
    )
    coverage_metrics = parse_coverage_output(coverage_out)

    print("  Running bandit...")
    _, bandit_out, _ = run_command(
        ["python", "-m", "bandit", "-r", "app/", "-f", "screen"], project_path
    )

    print("  Generating reports...")
    md_report = generate_markdown_report(
        pylint_metrics, coverage_metrics, bandit_out, args.name
    )

    md_path = output_path / "REPORT.md"
    md_path.write_text(md_report)
    print(f"  ✅ Generated: {md_path}")

    if "html" in args.format:
        html_report = generate_html_report(md_report, args.name)
        html_path = output_path / "REPORT.html"
        html_path.write_text(html_report)
        print(f"  ✅ Generated: {html_path}")

    if "pdf" in args.format:
        try:
            from weasyprint import HTML

            HTML(string=generate_html_report(md_report, args.name)).write_pdf(
                str(output_path / "REPORT.pdf")
            )
            print(f"  ✅ Generated: {output_path / 'REPORT.pdf'}")
        except ImportError:
            print("  ⚠️  weasyprint not installed, skipping PDF")

    print(f"\n✨ Reports generated in {output_path}")


if __name__ == "__main__":
    main()
