metadata: {}
pipeline:
  created_at: '2026-03-30T10:53:38.907910'
  id: PIPE-0F3787BB
  name: honey_pot_reporter
  version: 1.0.0
steps:
- name: Inference
  type: task
  version: v1.0
- expression: score > 50
  name: <wpipe.pipe.pipe.Condition object at 0x73ec19a932c0>
  type: condition
