metadata: {}
pipeline:
  created_at: '2026-03-30T10:54:39.055349'
  id: PIPE-7006132E
  name: honey_pot_reporter
  version: 1.0.0
steps:
- name: Inference
  type: task
  version: v1.0
- expression: score > 80
  name: <wpipe.pipe.pipe.Condition object at 0x76b07786ff20>
  type: condition
