metadata: {}
nested_pipelines:
- code_hash: sha256:f2a65d2f2f9bf4cd
  name: Inference
  pipeline_id: PIPE-F4DC45AD
pipeline:
  code_hash: sha256:9d9d3de6625733d6
  created_at: '2026-03-30T17:50:44.143797'
  id: PIPE-6B885D25
  name: honey_pot_reporter
  version: 1.0.0
steps:
- code_hash: sha256:f2a65d2f2f9bf4cd
  name: Inference
  pipeline_id: PIPE-F4DC45AD
  type: pipeline
  version: v1.0
- code_hash: null
  name: condition
  pipeline_id: null
  type: condition
  version: ''
