metadata: {}
nested_pipelines:
- code_hash: sha256:f2a65d2f2f9bf4cd
  name: Inference
  pipeline_id: PIPE-C4CBF08A
pipeline:
  code_hash: sha256:f73fb20c7ce06ce5
  created_at: '2026-03-30T17:52:58.850177'
  id: PIPE-CB19483E
  name: honey_pot_reporter
  version: 1.0.0
steps:
- code_hash: sha256:f2a65d2f2f9bf4cd
  name: Inference
  pipeline_id: PIPE-C4CBF08A
  type: pipeline
  version: v1.0
- code_hash: null
  name: condition
  pipeline_id: null
  type: condition
  version: ''
