metadata: {}
nested_pipelines:
- code_hash: sha256:f2a65d2f2f9bf4cd
  name: Inference
  pipeline_id: PIPE-47C45504
pipeline:
  code_hash: sha256:e8f4882670b1e25a
  created_at: '2026-03-30T17:52:53.927129'
  id: PIPE-14BAA114
  name: honey_pot_reporter
  version: 1.0.0
steps:
- code_hash: sha256:f2a65d2f2f9bf4cd
  name: Inference
  pipeline_id: PIPE-47C45504
  type: pipeline
  version: v1.0
- code_hash: null
  name: condition
  pipeline_id: null
  type: condition
  version: ''
