metadata: {}
nested_pipelines:
- code_hash: sha256:f2a65d2f2f9bf4cd
  name: Inference
  pipeline_id: PIPE-48E5B4CC
pipeline:
  code_hash: sha256:15e6fa7ec67ae3b7
  created_at: '2026-03-30T17:50:14.728910'
  id: PIPE-053640FD
  name: honey_pot_reporter
  version: 1.0.0
steps:
- code_hash: sha256:f2a65d2f2f9bf4cd
  name: Inference
  pipeline_id: PIPE-48E5B4CC
  type: pipeline
  version: v1.0
- code_hash: null
  name: condition
  pipeline_id: null
  type: condition
  version: ''
