metadata: {}
nested_pipelines:
- code_hash: sha256:f2a65d2f2f9bf4cd
  name: Inference
  pipeline_id: PIPE-C416F42A
pipeline:
  code_hash: sha256:074c96e1b36610db
  created_at: '2026-03-30T17:50:14.552521'
  id: PIPE-92C2C6D4
  name: honey_pot_reporter
  version: 1.0.0
steps:
- code_hash: sha256:f2a65d2f2f9bf4cd
  name: Inference
  pipeline_id: PIPE-C416F42A
  type: pipeline
  version: v1.0
- code_hash: null
  name: condition
  pipeline_id: null
  type: condition
  version: ''
