name: annotated_pipeline
registered_at: '2026-04-20T06:56:39.698174'
step_count: 5
steps:
- func: <function initialize at 0x7f36d659f600>
  name: initialize
  type: task
  version: v1.0
- func: <function process_batch_1 at 0x7f36af0c85e0>
  name: process_batch_1
  type: task
  version: v1.0
- func: <function checkpoint at 0x7f36af0c87c0>
  name: checkpoint
  type: task
  version: v1.0
- func: <function process_batch_2 at 0x7f36af0c8e00>
  name: process_batch_2
  type: task
  version: v1.0
- func: <function finalize at 0x7f36af0c8cc0>
  name: finalize
  type: task
  version: v1.0
