metadata: {}
pipeline:
  created_at: '2026-03-30T04:03:50.530981'
  id: PIPE-A1AA83CD
  name: weather_check_2
  version: 1.0.0
steps:
- name: read_temperature
  type: task
  version: v1.0
- expression: temperature > 30
  name: <wpipe.pipe.pipe.Condition object at 0x7f22ebb4dfd0>
  type: condition
- name: log_result
  type: task
  version: v1.0
