flowchart TD
  subgraph Pipeline_0 [Pipeline 1]
    n_Inicio_Pipeline_0((Inicio))
    n_Inicio_Pipeline_0 --> n_StepClass_L0_0["StepClass"]
    n_StepClass_L0_0 --> n_function_name_L0_1["function_name"]
    n_function_name_L0_1 --> n_Cond_L0_2{"valor > 100"}
    n_Cond_L0_2 -- True --> n_function_name_L0_2T0["function_name"]
    n_function_name_L0_2T0 --> n_StepClass2_L0_2T1["StepClass2"]
    n_Cond_L0_2 -- False --> n_StepClass3_L0_2F0["StepClass3"]
    n_Merge_L0_2(( ))
    n_StepClass2_L0_2T1 --> n_Merge_L0_2
    n_StepClass3_L0_2F0 --> n_Merge_L0_2
    n_Merge_L0_2 --> n_ForCall_L0_3[For Loop]
    n_ForCall_L0_3 --> n_SubFor_L0_3
    subgraph n_SubFor_L0_3 [For iterations=10<br/>status != 'error']
    n_ForInner_L0_3(( ))
    n_ForInner_L0_3 --> n_function_name5_L0_3F0["function_name5"]
    n_function_name5_L0_3F0 --> n_ParCall_L0_3F1[Parallel]
    n_ParCall_L0_3F1 --> n_SubPar_L0_3F1
    subgraph n_SubPar_L0_3F1 [Parallel max_workers=1]
    n_PStart_0_L0_3F1(( ))
    n_PStart_0_L0_3F1 --> n_function_name5_L0_3F1P00["function_name5"]

    n_PStart_1_L0_3F1(( ))
    n_PStart_1_L0_3F1 --> n_function_name6_L0_3F1P10["function_name6"]

    end
    n_PMerge_L0_3F1(( ))
    n_function_name5_L0_3F1P00 --> n_PMerge_L0_3F1
    n_function_name6_L0_3F1P10 --> n_PMerge_L0_3F1
    n_PMerge_L0_3F1 --> n_AdvancedStep_L0_3F2["AdvancedStep"]
    n_AdvancedStep_L0_3F2 --> n_ForCall_L0_3F3[For Loop]
    n_ForCall_L0_3F3 --> n_SubFor_L0_3F3
    subgraph n_SubFor_L0_3F3 [For iterations=10<br/>status != 'error']
    n_ForInner_L0_3F3(( ))
    n_ForInner_L0_3F3 --> n_AdvancedStep8_L0_3F3F0["AdvancedStep8"]
    n_AdvancedStep8_L0_3F3F0 --> n_function_name5_L0_3F3F1["function_name5"]

    end

    end
    n_SubFor_L0_3 --> n_ParCall_L0_4[Parallel]
    n_ParCall_L0_4 --> n_SubPar_L0_4
    subgraph n_SubPar_L0_4 [Parallel max_workers=2]
    n_PStart_0_L0_4(( ))
    n_PStart_0_L0_4 --> n_function_name5_L0_4P00["function_name5"]

    n_PStart_1_L0_4(( ))
    n_PStart_1_L0_4 --> n_pipe_2_L0_4P10["pipe_2"]

    end
    n_PMerge_L0_4(( ))
    n_function_name5_L0_4P00 --> n_PMerge_L0_4
    n_pipe_2_L0_4P10 --> n_PMerge_L0_4
    n_PMerge_L0_4 --> n_BGCall_L0_5["Background slow_step"]
    subgraph n_SubBG_L0_5 [Background Execution]
    n_BGExec_L0_5["slow_step"]
    end
    n_BGCall_L0_5 -. async .-> n_BGExec_L0_5

  end
  subgraph Pipeline_1 [Pipeline 2]
    n_Inicio_Pipeline_1((Inicio))
    n_Inicio_Pipeline_1 --> n_function_name5_L1_0["function_name5"]
    n_function_name5_L1_0 --> n_ParCall_L1_1[Parallel]
    n_ParCall_L1_1 --> n_SubPar_L1_1
    subgraph n_SubPar_L1_1 [Parallel max_workers=1]
    n_PStart_0_L1_1(( ))
    n_PStart_0_L1_1 --> n_function_name5_L1_1P00["function_name5"]

    n_PStart_1_L1_1(( ))
    n_PStart_1_L1_1 --> n_function_name6_L1_1P10["function_name6"]

    end
    n_PMerge_L1_1(( ))
    n_function_name5_L1_1P00 --> n_PMerge_L1_1
    n_function_name6_L1_1P10 --> n_PMerge_L1_1
    n_PMerge_L1_1 --> n_AdvancedStep_L1_2["AdvancedStep"]
    n_AdvancedStep_L1_2 --> n_ForCall_L1_3[For Loop]
    n_ForCall_L1_3 --> n_SubFor_L1_3
    subgraph n_SubFor_L1_3 [For iterations=10<br/>status != 'error']
    n_ForInner_L1_3(( ))
    n_ForInner_L1_3 --> n_AdvancedStep8_L1_3F0["AdvancedStep8"]
    n_AdvancedStep8_L1_3F0 --> n_function_name5_L1_3F1["function_name5"]

    end

  end
  subgraph Pipeline_2 [Pipeline 3]
    n_Inicio_Pipeline_2((Inicio))
    n_Inicio_Pipeline_2 --> n_function_name5_L2_0["function_name5"]
    n_function_name5_L2_0 --> n_function_name6_L2_1["function_name6"]

  end
  subgraph Pipeline_3 [Pipeline 4]
    n_Inicio_Pipeline_3((Inicio))
    n_Inicio_Pipeline_3 --> n_AdvancedStep8_L3_0["AdvancedStep8"]
    n_AdvancedStep8_L3_0 --> n_function_name5_L3_1["function_name5"]

  end
  subgraph Pipeline_4 [Pipeline 5]
    n_Inicio_Pipeline_4((Inicio))
    n_Inicio_Pipeline_4 --> n_function_name5_L4_0["function_name5"]
    n_function_name5_L4_0 --> n_pipe_2_L4_1["pipe_2"]

  end
