name: data_workflow
registered_at: '2026-04-20T06:56:34.136731'
step_count: 4
steps:
- func: <bound method Pipeline.run of <wpipe.pipe.pipe.Pipeline object at 0x7f3bf518c980>>
  name: collect_phase
  type: task
  version: v1.0
- func: <bound method Pipeline.run of <wpipe.pipe.pipe.Pipeline object at 0x7f3bf5187610>>
  name: process_phase
  type: task
  version: v1.0
- func: <bound method Pipeline.run of <wpipe.pipe.pipe.Pipeline object at 0x7f3bf5187d90>>
  name: export_phase
  type: task
  version: v1.0
- func: <function send_notification at 0x7f3bf5061300>
  name: notification
  type: task
  version: v1.0
