metadata: {}
pipeline:
  created_at: '2026-03-30T04:13:35.937795'
  id: PIPE-DA65166E
  name: data_processor
  version: 1.0.0
steps:
- name: transform
  type: task
  version: v1.0
- name: enrich
  type: task
  version: v1.0
- name: aggregate
  type: task
  version: v1.0
