metadata: {}
pipeline:
  created_at: '2026-04-09T06:56:55.318648'
  id: PIPE-6E49F43F
  name: viaje
  version: 1.0.0
steps:
- expression: null
  name: <wpipe.pipe.pipe.For object at 0x7f2bab7296d0>
  type: condition
