import * as vscode from 'vscode';
import * as path from 'path';
import { parser } from '@lezer/python';
import { ConfigManager } from '../core/config';

export class DAGPanel {
    public static currentPanel: DAGPanel | undefined;
    private readonly _panel: vscode.WebviewPanel;
    private _disposables: vscode.Disposable[] = [];

    public static async createOrShow(uri: vscode.Uri, doc: vscode.TextDocument) {
        if (DAGPanel.currentPanel) { 
            DAGPanel.currentPanel._panel.reveal(); 
            await DAGPanel.currentPanel._update(doc, true); 
            return; 
        }
        const p = vscode.window.createWebviewPanel('wpipeDAG', 'WPipe Analysis', vscode.ViewColumn.Two, { 
            enableScripts: true,
            retainContextWhenHidden: true
        });
        DAGPanel.currentPanel = new DAGPanel(p, doc);
    }

    public highlightNodes(nodeNames: string[], status: 'error' | 'success' | 'running') {
        this._panel.webview.postMessage({
            command: 'highlightNodes',
            nodes: nodeNames,
            status: status
        });
    }

    private constructor(p: vscode.WebviewPanel, doc: vscode.TextDocument) {
        this._panel = p;
        this._panel.onDidDispose(() => { DAGPanel.currentPanel = undefined; }, null, this._disposables);
        
        // Inicialización
        this._update(doc, true);
        
        this._panel.webview.onDidReceiveMessage(async message => {
            if (message.command === 'downloadImage') {
                const saveUri = await vscode.window.showSaveDialog({
                    defaultUri: vscode.Uri.file(message.fileName),
                    filters: message.format === 'png' ? { 'PNG Image': ['png'] } : { 'SVG Image': ['svg'] }
                });
                if (saveUri) {
                    let data: Uint8Array;
                    if (message.format === 'png') {
                        const base64Data = message.content.replace(/^data:image\/png;base64,/, "");
                        data = Buffer.from(base64Data, 'base64');
                    } else {
                        data = new TextEncoder().encode(message.content);
                    }
                    await vscode.workspace.fs.writeFile(saveUri, data);
                    vscode.window.showInformationMessage(`✅ DAG exported as ${message.format.toUpperCase()} successfully.`);
                }
            } else if (message.command === 'gotoLine') {
                const line = parseInt(message.line);
                if (!isNaN(line)) {
                    const editor = vscode.window.activeTextEditor;
                    if (editor && editor.document === doc) {
                        const pos = new vscode.Position(line, 0);
                        editor.selection = new vscode.Selection(pos, pos);
                        editor.revealRange(new vscode.Range(pos, pos), vscode.TextEditorRevealType.InCenter);
                    } else {
                        // If the document is not active, try to open it
                        const newDoc = await vscode.workspace.openTextDocument(doc.uri);
                        const newEditor = await vscode.window.showTextDocument(newDoc);
                        const pos = new vscode.Position(line, 0);
                        newEditor.selection = new vscode.Selection(pos, pos);
                        newEditor.revealRange(new vscode.Range(pos, pos), vscode.TextEditorRevealType.InCenter);
                    }
                }
            }
        }, null, this._disposables);

        // SOLO escribimos archivo al guardar si el panel está abierto para este documento
        vscode.workspace.onDidSaveTextDocument(e => { 
            if (e === doc) this._update(doc, true); 
        }, null, this._disposables);

        // Al cambiar de editor, solo actualizamos la VISTA, no escribimos archivo (evita duplicidad innecesaria)
        vscode.window.onDidChangeActiveTextEditor(e => { 
            if (e && e.document.languageId === 'python') this._update(e.document, false); 
        }, null, this._disposables);
    }

    private async _update(doc: vscode.TextDocument, forceBackup: boolean = false) {
        const fileName = path.basename(doc.uri.fsPath);
        const res = this.parse(doc, fileName);

        // SAVE TO FILE (Solo si está habilitado y es una acción "manual" o guardado)
        if (forceBackup && await ConfigManager.isBackupEnabled()) {
            try {
                const dir = path.dirname(doc.uri.fsPath);
                const base = path.basename(doc.uri.fsPath, path.extname(doc.uri.fsPath));
                // Nueva extensión solicitada: .wpipe.mermaid
                const mdPath = path.join(dir, `${base}.wpipe.mermaid`);
                const content = `%% Generated by WPipe Tools\n${res.graph}`;
                await vscode.workspace.fs.writeFile(vscode.Uri.file(mdPath), new TextEncoder().encode(content));
            } catch (e) {}
        }

        this._panel.webview.html = this._getHtml(fileName, res.graph, res.stats, res.bigO, res.suggestions);
    }

    private _getHtml(fileName: string, graph: string, stats: any, bigO: string, suggestions: string[] = []) {
        const now = new Date().toLocaleTimeString();
        const cspSource = this._panel.webview.cspSource;
        const suggestionsHtml = suggestions.map(s => `<div class="card" style="margin-top:10px; border-left:3px solid #007acc; font-size:10px;">${s}</div>`).join('');

        return `<html>
        <head>
            <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src ${cspSource} https://cdn.jsdelivr.net 'unsafe-inline'; style-src ${cspSource} 'unsafe-inline'; img-src ${cspSource} data:;">
            <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/svg-pan-zoom@3.6.1/dist/svg-pan-zoom.min.js"></script>
            <script>
                const vscode = acquireVsCodeApi();
                let pz = null;

                window.handleNodeClick = function(line) {
                    vscode.postMessage({ command: 'gotoLine', line: line });
                };

                window.addEventListener('message', event => {
                    const message = event.data;
                    if (message.command === 'highlightNodes') {
                        const { nodes, status } = message;
                        const svgElement = document.querySelector('svg');
                        if (!svgElement) return;

                        // Reset previous highlights or apply new ones
                        // In Mermaid, nodes have IDs like 'nLuid_LX' (from our parser)
                        // This logic might need refinement to match step names
                        const allNodes = svgElement.querySelectorAll('.node');
                        allNodes.forEach(node => {
                            const label = node.querySelector('.nodeLabel');
                            if (label) {
                                const text = label.textContent || '';
                                if (nodes.some(n => text.includes(n))) {
                                    if (status === 'error') {
                                        node.style.stroke = '#ff4d4d';
                                        node.style.strokeWidth = '4px';
                                        node.classList.add('node-error');
                                    }
                                }
                            }
                        });
                    }
                });

                async function initMermaid() {
                    const container = document.getElementById('mermaid-container');
                    try {
                        mermaid.initialize({
                            startOnLoad: false,
                            theme: 'base',
                            themeVariables: {
                                primaryColor: '#1e1e1e',
                                primaryTextColor: '#fff',
                                primaryBorderColor: '#007acc',
                                lineColor: '#555',
                                secondaryColor: '#ce9178',
                                tertiaryColor: '#1e1e1e',
                                mainBkg: 'transparent'
                            },
                            securityLevel: 'loose',
                            flowchart: { curve: 'basis', htmlLabels: true }
                        });

                        const { svg } = await mermaid.render('mermaid-svg', \`${graph}\`);
                        container.innerHTML = svg;

                        const svgElement = container.querySelector('svg');
                        if (svgElement) {
                            svgElement.style.width = '100%';
                            svgElement.style.height = '100%';
                            svgElement.style.display = 'block';
                            
                            if (pz) pz.destroy();
                            pz = svgPanZoom(svgElement, {
                                zoomEnabled: true,
                                controlIconsEnabled: false,
                                fit: true,
                                center: true,
                                minZoom: 0.001,
                                maxZoom: 100
                            });

                            document.getElementById('zoom-in').onclick = () => pz.zoomIn();
                            document.getElementById('zoom-out').onclick = () => pz.zoomOut();
                            document.getElementById('zoom-reset').onclick = () => { pz.resetZoom(); pz.center(); };
                            
                            document.getElementById('download-svg').onclick = () => {
                                try {
                                    const serializer = new XMLSerializer();
                                    let source = serializer.serializeToString(svgElement);
                                    source = '<?xml version="1.0" standalone="no"?>\\r\\n' + source;
                                    vscode.postMessage({
                                        command: 'downloadImage',
                                        content: source,
                                        format: 'svg',
                                        fileName: '${fileName.replace(/\.[^/.]+$/, "")}_dag.svg'
                                    });
                                } catch (err) {
                                    console.error('Download error:', err);
                                }
                            };

                            document.getElementById('download-png').onclick = () => {
                                try {
                                    const serializer = new XMLSerializer();
                                    const svgData = serializer.serializeToString(svgElement);
                                    const canvas = document.createElement('canvas');
                                    const ctx = canvas.getContext('2d');
                                    const img = new Image();
                                    const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
                                    const url = URL.createObjectURL(svgBlob);

                                    img.onload = () => {
                                        canvas.width = img.width * 2; // High DPI
                                        canvas.height = img.height * 2;
                                        ctx.fillStyle = 'white'; // Background
                                        ctx.fillRect(0, 0, canvas.width, canvas.height);
                                        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
                                        URL.revokeObjectURL(url);
                                        const pngData = canvas.toDataURL('image/png');
                                        vscode.postMessage({
                                            command: 'downloadImage',
                                            content: pngData,
                                            format: 'png',
                                            fileName: '${fileName.replace(/\.[^/.]+$/, "")}_dag.png'
                                        });
                                    };
                                    img.src = url;
                                } catch (err) {
                                    console.error('PNG Download error:', err);
                                }
                            };
                        }
                    } catch (e) {
                        container.innerHTML = '<div style="padding:20px; color:#ff4d4d; background:#111; border-radius:8px;">❌ Mermaid Render Error: ' + e.message + '</div>';
                    }
                }

                window.addEventListener('load', initMermaid);
            </script>
            <style>
                body { background: #0a0a0a; color: #d4d4d4; font-family: 'Segoe UI', sans-serif; margin: 0; padding: 0; overflow: hidden; display: flex; flex-direction: column; height: 100vh; width: 100vw; }
                .glass-header { background: #1a1a1a; padding: 10px 20px; border-bottom: 2px solid #007acc; display: flex; justify-content: space-between; align-items: center; z-index: 1000; flex-shrink: 0; }
                .main-layout { display: flex; flex: 1; overflow: hidden; position: relative; }
                .sidebar { width: 240px; background: #111; border-right: 1px solid #222; padding: 15px; display: flex; flex-direction: column; gap: 15px; z-index: 500; flex-shrink: 0; overflow-y: auto; }
                .canvas { flex: 1; position: relative; background: #000; overflow: hidden; }
                #mermaid-container { position: absolute; top:0; left:0; width: 100%; height: 100%; z-index: 10; display: flex; justify-content: center; align-items: center; background: transparent; }
                .card { background: #1e1e1e; border: 1px solid #333; border-radius: 6px; padding: 12px; }
                .stat-item { display: flex; justify-content: space-between; font-size: 11px; margin-bottom: 6px; }
                .complexity-box { text-align: center; padding: 12px; border-radius: 8px; background: #161616; border-left: 3px solid #ce9178; }
                .footer { background: #111; padding: 5px 20px; border-top: 1px solid #222; font-size: 9px; color: #444; display: flex; justify-content: space-between; flex-shrink: 0; }
                .toolbar { position: absolute; bottom: 20px; right: 20px; display: flex; gap: 5px; background: rgba(30,30,30,0.85); padding: 6px; border-radius: 8px; border: 1px solid #444; z-index: 2000; }
                .toolbar button { background: #444; color: white; border: none; width: 30px; height: 32px; border-radius: 4px; cursor: pointer; font-weight: bold; font-size: 16px; transition: 0.2s; }
                .toolbar button:hover { background: #007acc; }
                .btn-primary { width: 100%; padding: 10px; background: #007acc; color: white; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; font-size: 11px; }
                .btn-primary:hover { background: #0098ff; }
                .node-error rect, .node-error circle, .node-error polygon, .node-error path {
                    fill: rgba(255, 77, 77, 0.3) !important;
                    stroke: #ff4d4d !important;
                    stroke-width: 3px !important;
                }
            </style>
        </head>
        <body>
            <header class="glass-header">
                <div><h1 style="margin:0;font-size:15px;font-weight:600;color:#4fc1ff;">🚀 WPipe Analysis Mode</h1></div>
                <div style="text-align:right"><div style="font-size:11px;color:#eee;">${fileName}</div><div style="font-size:8px;color:#555;">Live ${now}</div></div>
            </header>
            <div class="main-layout">
                <aside class="sidebar">
                    <div class="card">
                        <h3 style="margin:0 0 10px 0; font-size:10px; color: #888;">STATS</h3>
                        <div class="stat-item"><span>Steps</span><b>${stats.steps}</b></div>
                        <div class="stat-item"><span>Logic Blocks</span><b>${stats.logic}</b></div>
                        <div class="stat-item"><span>Pipelines</span><b>${stats.pipes}</b></div>
                    </div>
                    <div class="complexity-box">
                        <span style="font-size:8px;color:#666;">COMPUTATIONAL COST</span>
                        <div style="font-size:20px;font-weight:bold;color:#ce9178;margin:2px 0;">${bigO}</div>
                    </div>
                    ${suggestionsHtml}
                    <div style="margin-top:auto; display:flex; flex-direction:column; gap:8px;">
                        <button id="download-svg" class="btn-primary">💾 Download SVG</button>
                        <button id="download-png" class="btn-primary" style="background:#444;">🖼️ Download PNG</button>
                    </div>
                </aside>
                <main class="canvas">
                    <div id="mermaid-container"></div>
                    <div class="toolbar">
                        <button id="zoom-out" title="Zoom Out">−</button>
                        <button id="zoom-reset" title="Reset Center">⟲</button>
                        <button id="zoom-in" title="Zoom In">+</button>
                    </div>
                </main>
            </div>
            <footer class="footer">
                <div>William Rodriguez (wisrovi)</div>
                <div>Engine: <b>Mermaid v10</b></div>
            </footer>
        </body>
        </html>`;
    }

    private parse(doc: vscode.TextDocument, fileName: string): any {
        const content = doc.getText();
        let g = "flowchart TD\n  classDef step fill:#1e1e1e,stroke:#007acc,stroke-width:2px,color:#fff,rx:5,ry:5,cursor:pointer\n  classDef logic fill:#1e1e1e,stroke:#ce9178,stroke-width:2px,color:#fff,rx:2,ry:2,cursor:pointer\n  classDef startN fill:#007acc,stroke:#007acc,color:#fff\n";
        
        let totalSteps = 0; let totalLogic = 0; let maxDepth = 0;
        const tree = parser.parse(content);
        const pipelineInstances: any[] = [];
        const addStateCalls: any[] = [];

        tree.iterate({
            enter: (node) => {
                if (node.name === 'CallExpression') {
                    const callText = content.substring(node.from, node.to);
                    if (callText.includes('.set_steps(') || (callText.startsWith('Pipeline(') && callText.includes('steps='))) {
                        pipelineInstances.push({ text: callText, from: node.from, to: node.to });
                    } else if (callText.includes('.add_state(')) {
                        addStateCalls.push({ text: callText, from: node.from, to: node.to });
                    }
                }
            }
        });

        const seenPipelines = new Set<string>();

        pipelineInstances.forEach((inst) => {
            const pipeVar = inst.text.split('.')[0].split('(')[0].trim() || "Pipeline";
            if (seenPipelines.has(pipeVar)) return;
            seenPipelines.add(pipeVar);

            const uid = Math.random().toString(36).substr(2, 5);
            g += `  subgraph sg_${uid} ["📦 ${pipeVar} (in ${fileName})"]\n    direction TD\n    start_${uid}(( )):::startN\n`;

            let stepsContent = '';
            let stepsOffset = inst.from;
            const m1 = inst.text.match(/(?:set_steps|steps)\s*\(\s*\[([\s\S]*?)\]\s*\)/);
            const m2 = inst.text.match(/steps\s*=\s*\[([\s\S]*?)\]/);
            if (m1) {
                stepsContent = m1[1];
                stepsOffset += inst.text.indexOf(m1[1]);
            } else if (m2) {
                stepsContent = m2[1];
                stepsOffset += inst.text.indexOf(m2[1]);
            }

            const res = this.parseRec(doc, stepsContent, stepsOffset, `start_${uid}`, "L" + uid, 0);
            g += res.graph.split('\n').map((l: string) => l.trim() ? "    " + l : "").join('\n') + "\n";
            totalSteps += res.steps; totalLogic += res.logic; if (res.depth > maxDepth) maxDepth = res.depth;
            
            let lastId = res.lastId;
            let lastLabel = res.lastIncomingLabel;

            addStateCalls.forEach((addCall) => {
                if (addCall.text.startsWith(pipeVar + '.add_state(')) {
                    const am = addCall.text.match(/\.add_state\s*\(([\s\S]*?)\)/);
                    if (am) {
                        const amOffset = addCall.from + addCall.text.indexOf(am[1]);
                        const res2 = this.parseRec(doc, am[1], amOffset, lastId, "A" + Math.random().toString(36).substr(2, 3), 0, lastLabel);
                        g += res2.graph.split('\n').map((l: string) => l.trim() ? "    " + l : "").join('\n') + "\n";
                        totalSteps += res2.steps; totalLogic += res2.logic; if (res2.depth > maxDepth) maxDepth = res2.depth;
                        lastId = res2.lastId;
                        lastLabel = res2.lastIncomingLabel;
                    }
                }
            });
            g += "  end\n";
        });

        let bigO = "O(n)"; if (maxDepth === 1) bigO = "O(n²)"; else if (maxDepth > 1) bigO = `O(n^${maxDepth + 1})`;
        
        const suggestions: string[] = [];
        if (totalSteps > 5 && totalLogic === 0) {
            suggestions.push("💡 Tip: Your pipeline is linear. Consider using 'Parallel' if steps are independent.");
        }

        return { 
            graph: seenPipelines.size > 0 ? g : "flowchart TD\n  NoPipe[No pipeline detected]", 
            stats: { steps: totalSteps, logic: totalLogic, pipes: seenPipelines.size }, 
            bigO,
            suggestions
        };
    }

    private parseRec(doc: vscode.TextDocument, content: string, offset: number, prev: string, prefix: string, depth: number, incomingLabel: string = ""): any {
        let graph = ""; let curr = prev; let sCount = 0; let lCount = 0; let maxSubDepth = depth;
        let currentLabel = incomingLabel;

        const splitWithOffsets = (c: string, baseOffset: number) => {
            const r: {text: string, offset: number}[] = []; let cur = ""; let d = 0; let start = 0;
            for (let i = 0; i < c.length; i++) {
                if (c[i] === '[' || c[i] === '(') d++; else if (c[i] === ']' || c[i] === ')') d--;
                if (c[i] === ',' && d === 0) { 
                    r.push({ text: cur.trim(), offset: baseOffset + start + (cur.length - cur.trimStart().length) }); 
                    cur = ""; start = i + 1; 
                } else cur += c[i];
            }
            if (cur.trim()) r.push({ text: cur.trim(), offset: baseOffset + start + (cur.length - cur.trimStart().length) }); 
            return r;
        };

        splitWithOffsets(content, offset).forEach((item, i) => {
            const tr = item.text; if (!tr) return;
            const line = doc.positionAt(item.offset).line;
            const id = "n" + prefix + i + "_L" + line;
            const edge = currentLabel ? `-- ${currentLabel} -->` : "-->";
            currentLabel = "";

            if (tr.startsWith('Condition(')) {
                lCount++; 
                const exprMatch = tr.match(/expression\s*=\s*(["'])(.*?)\1/);
                const expr = exprMatch ? exprMatch[2] : "Condition";
                graph += `  ${curr} ${edge} ${id}{"${expr}"}:::logic\n`;
                graph += `  click ${id} call handleNodeClick("${line}")\n`;
                
                const tCont = this.ext(tr, 'branch_true'); const fCont = this.ext(tr, 'branch_false'); const mid = id + "_m";
                if (tCont) { 
                    const tOffset = item.offset + tr.indexOf(tCont);
                    const r = this.parseRec(doc, tCont, tOffset, id, id + "T", depth, "True"); 
                    graph += r.graph + `  ${r.lastId} --> ${mid}(( ))\n`; 
                    sCount += r.steps; lCount += r.logic; if (r.depth > maxSubDepth) maxSubDepth = r.depth; 
                }
                else graph += `  ${id} -- True --> ${mid}(( ))\n`;
                
                if (fCont) { 
                    const fOffset = item.offset + tr.indexOf(fCont);
                    const r = this.parseRec(doc, fCont, fOffset, id, id + "F", depth, "False"); 
                    graph += r.graph + `  ${r.lastId} --> ${mid}(( ))\n`; 
                    sCount += r.steps; lCount += r.logic; if (r.depth > maxSubDepth) maxSubDepth = r.depth; 
                }
                else graph += `  ${id} -- False --> ${mid}(( ))\n`;
                curr = mid;
            } else if (tr.startsWith('Parallel(')) {
                lCount++; graph += `  ${curr} ${edge} ${id}[[" ⚡ Parallel "]]:::logic\n`;
                graph += `  click ${id} call handleNodeClick("${line}")\n`;
                const pCont = this.ext(tr, 'steps'); const mid = id + "_m";
                if (pCont) {
                    const pOffset = item.offset + tr.indexOf(pCont);
                    this.smartSplitWithOffsets(pCont, pOffset).forEach((ps, pi) => {
                        const r = this.parseRec(doc, ps.text, ps.offset, id, id + "P" + pi, depth, "flow");
                        graph += r.graph + `  ${r.lastId} --> ${mid}(( ))\n`;
                        sCount += r.steps; lCount += r.logic; if (r.depth > maxSubDepth) maxSubDepth = r.depth;
                    });
                } else { graph += `  ${id} --> ${mid}(( ))\n`; }
                curr = mid;
            } else if (tr.startsWith('For(')) {
                lCount++; graph += `  ${curr} ${edge} ${id}[[" 🔄 For Loop "]]:::logic\n`;
                graph += `  click ${id} call handleNodeClick("${line}")\n`;
                const fCont = this.ext(tr, 'steps');
                if (fCont) { 
                    const fOffset = item.offset + tr.indexOf(fCont);
                    const r = this.parseRec(doc, fCont, fOffset, id, id + "F", depth + 1, "body"); 
                    graph += r.graph + `  ${r.lastId} --> ${id}\n`; sCount += r.steps; lCount += r.logic; if (r.depth > maxSubDepth) maxSubDepth = r.depth; 
                }
                curr = id;
                currentLabel = "exit";
            } else if (tr.startsWith('Background(')) {
                lCount++; 
                const lblMatch = tr.match(/Background\((.*?)\)/);
                const lbl = lblMatch ? lblMatch[1].split(',')[0].trim() : "BG Task";
                graph += `  ${curr} -. async .-> ${id}((" ⚡ ${lbl} ")):::step\n`;
                graph += `  click ${id} call handleNodeClick("${line}")\n`;
            } else {
                let lbl = tr.split('(')[0].replace(/[\[\]]/g, '').trim();
                if (lbl) { 
                    sCount++; graph += `  ${curr} ${edge} ${id}[" 🚀 ${lbl} "]:::step\n`; 
                    graph += `  click ${id} call handleNodeClick("${line}")\n`;
                    curr = id; 
                }
            }
        });
        return { graph, lastId: curr, steps: sCount, logic: lCount, depth: maxSubDepth, lastIncomingLabel: currentLabel };
    }

    private smartSplitWithOffsets(c: string, baseOffset: number): {text: string, offset: number}[] {
        const r: {text: string, offset: number}[] = []; let cur = ""; let d = 0; let start = 0;
        for (let i = 0; i < c.length; i++) {
            if (c[i] === '[' || c[i] === '(') d++; else if (c[i] === ']' || c[i] === ')') d--;
            if (c[i] === ',' && d === 0) { 
                r.push({ text: cur.trim(), offset: baseOffset + start + (cur.length - cur.trimStart().length) }); 
                cur = ""; start = i + 1; 
            } else cur += c[i];
        }
        if (cur.trim()) r.push({ text: cur.trim(), offset: baseOffset + start + (cur.length - cur.trimStart().length) }); 
        return r;
    }
    private ext(c: string, a: string): string | null {
        const m = c.match(new RegExp(`${a}\\s*=\\s*\\[`));
        if (m) {
            let s = m.index! + m[0].length; let d = 1;
            for (let i = s; i < c.length; i++) { if (c[i] === '[') d++; else if (c[i] === ']') d--; if (d === 0) return c.substring(s, i); }
        }
        return null;
    }
    private smartSplit(c: string): string[] {
        const r: string[] = []; let cur = ""; let d = 0;
        for (let i = 0; i < c.length; i++) {
            if (c[i] === '[' || c[i] === '(') d++; else if (c[i] === ']' || c[i] === ')') d--;
            if (c[i] === ',' && d === 0) { r.push(cur.trim()); cur = ""; } else cur += c[i];
        }
        if (cur.trim()) r.push(cur.trim()); return r;
    }
}
