import * as vscode from 'vscode';
import * as path from 'path';

export async function createNewStepWizard() {
    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (!workspaceFolders) {
        vscode.window.showErrorMessage('Please open a workspace before creating a new step.');
        return;
    }

    const rootPath = workspaceFolders[0].uri.fsPath;
    const statesPath = path.join(rootPath, 'states');

    // 1. Ask for Step Name
    const stepName = await vscode.window.showInputBox({
        prompt: 'Enter the name of the new step (e.g. DataProcessor)',
        placeHolder: 'MyNewStep',
        validateInput: (value) => {
            if (!value) return 'Step name is required';
            if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(value)) return 'Invalid Python identifier';
            return null;
        }
    });

    if (!stepName) return;

    // Convert to PascalCase for Class naming convention
    const formattedStepName = stepName
        .split(/[_-]/)
        .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
        .join('');

    // 2. Prepare file names
    const fileName = stepName.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase() + '.py';
    const filePath = path.join(statesPath, fileName);

    // 3. Advanced Step Template (based on snippet)
    const template = `from wpipe import step, to_obj
from wpipe.timeout import timeout_sync
from typing import Any
from pydantic import BaseModel

class ${formattedStepName}Context(BaseModel):
    field: str

@step(
    name="${formattedStepName}",
    version="v1.0",
    timeout=10,
    description="Description of the step ${formattedStepName}",
    tags=["custom"],
    retry_count=3,
    retry_delay=0.01,
)
class ${formattedStepName}:
    """
    Advanced WPipe State: ${formattedStepName}
    Generated by WPipe Tools Wizard.
    """
    
    def __init__(self, config: str = "value"):
        self.config = config

    @timeout_sync(seconds=2)
    @to_obj(${formattedStepName}Context)
    def __call__(self, context: Any) -> Any:
        # Professional logic here
        print(f"🚀 Executing ${formattedStepName} with config: {self.config}")
        return context
`;

    try {
        // Create states folder and __init__.py if they don't exist
        const statesUri = vscode.Uri.file(statesPath);
        await vscode.workspace.fs.createDirectory(statesUri);
        
        const initUri = vscode.Uri.joinPath(statesUri, '__init__.py');
        let initContent = '';
        try {
            const existingInit = await vscode.workspace.fs.readFile(initUri);
            initContent = new TextDecoder().decode(existingInit);
        } catch {
            // File doesn't exist, will create new
        }

        // Add import to __init__.py
        const importLine = `from .${fileName.replace('.py', '')} import ${formattedStepName}\n`;
        if (!initContent.includes(importLine)) {
            initContent += importLine;
            await vscode.workspace.fs.writeFile(initUri, new TextEncoder().encode(initContent));
        }

        // Write the new step file
        const fileUri = vscode.Uri.file(filePath);
        await vscode.workspace.fs.writeFile(fileUri, new TextEncoder().encode(template));

        // Open the new file
        const doc = await vscode.workspace.openTextDocument(fileUri);
        await vscode.window.showTextDocument(doc);

        vscode.window.showInformationMessage(`✅ Step '${formattedStepName}' created successfully in states/${fileName}`);
    } catch (err: any) {
        vscode.window.showErrorMessage(`❌ Failed to create step: ${err.message}`);
    }
}
