metadata: {}
pipeline:
  created_at: '2026-03-29T09:46:17.576332'
  id: PIPE-B6F9645A
  name: error_example
  version: 1.0.0
steps:
- name: validate_input
  type: task
  version: v1.0
- name: process_data
  type: task
  version: v1.0
- name: finalize
  type: task
  version: v1.0
