metadata: {}
pipeline:
  created_at: '2026-03-29T09:46:35.918703'
  id: PIPE-276F7822
  name: data_export
  version: 1.0.0
steps:
- name: format
  type: task
  version: v1.0
- name: compress
  type: task
  version: v1.0
- name: upload
  type: task
  version: v1.0
