metadata: {}
pipeline:
  created_at: '2026-03-29T09:22:43.310436'
  id: PIPE-356457BE
  name: data_transformation
  version: 1.0.0
steps:
- name: normalize
  type: task
  version: v1.0
- name: enrich
  type: task
  version: v1.0
- name: aggregate
  type: task
  version: v1.0
