metadata: {}
pipeline:
  created_at: '2026-03-29T09:30:03.655565'
  id: PIPE-40F95872
  name: weather_hot
  version: 1.0.0
steps:
- name: read_temp
  type: task
  version: v1.0
- expression: temp > 30
  name: <wpipe.pipe.pipe.Condition object at 0x7f85f3b25950>
  type: condition
- name: log_action
  type: task
  version: v1.0
