metadata: {}
pipeline:
  created_at: '2026-03-29T09:46:43.690072'
  id: PIPE-738008B9
  name: api_notification
  version: 1.0.0
steps:
- name: fetch_data
  type: task
  version: v1.0
- name: process_data
  type: task
  version: v1.0
- name: notify_webhook
  type: task
  version: v1.0
