metadata: {}
pipeline:
  created_at: '2026-03-29T09:22:16.459786'
  id: PIPE-EDFC3C1B
  name: Pipeline
  version: 1.0.0
steps:
- name: Fetch Data
  type: task
  version: v1.0
- name: Process Records
  type: task
  version: v1.0
- name: Calculate Stats
  type: task
  version: v1.0
