metadata: {}
pipeline:
  created_at: '2026-03-29T09:44:04.893792'
  id: PIPE-DDCD2226
  name: weather_normal
  version: 1.0.0
steps:
- name: read_temp
  type: task
  version: v1.0
- expression: temp > 30
  name: <wpipe.pipe.pipe.Condition object at 0x7f652d72fad0>
  type: condition
- name: log_action
  type: task
  version: v1.0
