metadata: {}
pipeline:
  created_at: '2026-03-29T09:46:34.727770'
  id: PIPE-A25A7A72
  name: data_validation
  version: 1.0.0
steps:
- name: check_schema
  type: task
  version: v1.0
- name: validate_fields
  type: task
  version: v1.0
- name: clean_invalid
  type: task
  version: v1.0
