#!/usr/bin/env python3
"""
Git Mapper - Generate granular commits script

Usage:
    python generate_commits.py --output mapper_files.sh
"""

import argparse
import subprocess
from pathlib import Path


CONVENTIONAL_PREFIXES = {
    ".py": "FEATURE",
    ".js": "FEATURE",
    ".ts": "FEATURE",
    ".md": "DOC",
    ".txt": "DOC",
    ".yaml": "CONFIG",
    ".yml": "CONFIG",
    ".json": "CONFIG",
    ".toml": "CONFIG",
    ".ini": "CONFIG",
    ".sh": "CONFIG",
    ".dockerfile": "CONFIG",
    "Dockerfile": "CONFIG",
    "README": "DOC",
}


def get_prefix(file_path: Path) -> str:
    """Determine conventional commit prefix based on file extension."""
    ext = file_path.suffix.lower()
    if file_path.name.startswith("Dockerfile"):
        return "CONFIG"
    return CONVENTIONAL_PREFIXES.get(ext, "FEATURE")


def is_new_file(file_path: Path) -> bool:
    """Check if file is untracked in git."""
    result = subprocess.run(
        ["git", "ls-files", "--others", "--", str(file_path)],
        capture_output=True,
        text=True,
    )
    return bool(result.stdout.strip())


def generate_commit_message(file_path: Path) -> str:
    """Generate descriptive commit message for a file."""
    prefix = get_prefix(file_path)

    name = file_path.name
    action = "Add"

    if not is_new_file(file_path):
        action = "Update"

    desc = name.replace("_", " ").replace("-", " ").replace(".py", "")

    return f"[{prefix}] {action} {desc}"


def generate_script(project_path: Path) -> str:
    """Generate the bash script for granular commits."""
    script = """#!/bin/bash
# =============================================================================
# Granular Git Commits Script
# Generated by git-mapper skill
# =============================================================================

set -e

echo "Starting granular commit process..."

"""

    for file_path in sorted(project_path.rglob("*")):
        if not file_path.is_file():
            continue
        if ".git" in file_path.parts:
            continue
        if file_path.name == "mapper_files.sh":
            continue

        rel_path = file_path.relative_to(project_path)
        message = generate_commit_message(file_path)

        script += f'''
# {rel_path}
git add "{rel_path}"
git commit -m "{message}"
'''

    script += """
echo "Done! All files committed."
"""

    return script


def main():
    parser = argparse.ArgumentParser(description="Generate granular commit script")
    parser.add_argument(
        "--output", "-o", default="mapper_files.sh", help="Output script path"
    )
    parser.add_argument("--path", "-p", default=".", help="Project path")
    args = parser.parse_args()

    project_path = Path(args.path).resolve()
    script_content = generate_script(project_path)

    output_path = Path(args.output)
    output_path.write_text(script_content)
    output_path.chmod(0o755)

    print(f"✅ Generated: {output_path}")
    print(
        f"   Files to commit: {sum(1 for _ in project_path.rglob('*') if _.is_file() and '.git' not in _.parts)}"
    )


if __name__ == "__main__":
    main()
