metadata: {}
pipeline:
  created_at: '2026-03-30T04:03:56.908921'
  id: PIPE-F81CB480
  name: load_data
  version: 1.0.0
steps:
- name: prepare_target
  type: task
  version: v1.0
- name: insert_records
  type: task
  version: v1.0
- name: verify_load
  type: task
  version: v1.0
