metadata: {}
pipeline:
  created_at: '2026-03-30T04:03:56.816352'
  id: PIPE-75101EB9
  name: extract_data
  version: 1.0.0
steps:
- name: connect_source
  type: task
  version: v1.0
- name: fetch_records
  type: task
  version: v1.0
- name: parse_data
  type: task
  version: v1.0
